//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public int Id { get; set; }
        public int ChapId { get; set; }
        public int UserID { get; set; }
        public int Score { get; set; }
        public string Suggestion { get; set; }
        public int Total { get; set; }
        public System.DateTime testDate { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Users Users { get; set; }
    }
}
